name: Terraform Plan

on:
  push:
    branches: ["main"]
    paths:
      - "terraform/**"
      - ".github/workflows/**"
  workflow_dispatch:

# Required for GitHub OIDC -> AWS STS AssumeRoleWithWebIdentity
permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-main
  cancel-in-progress: false

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: ca-central-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.3"

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -input=false -var-file=env/dev.tfvars
